version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    build:
      context: .
      dockerfile: DockerfileRedis
    ports:
      - "5200:6379"
    env_file:
      - ./.env
